shared: &shared
  aws_access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  aws_secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  aws_s3_bucket: remark-social-<%= Rails.env %>

development:
  <<: *shared

production:
  <<: *shared
